### PR TITLE
Add styles to reservation Update Slice Buttons

### LINKED ISSUE #27: [2pt] Add a State To Change BG in reservation Page
- [ ] Use the design based on the "Book a vespa test-ride" green background and add all necessary inputs.
- [ ] Update Mobile to be responsive

### PR DESCRIPTION
**Pull request by PabloBona**
### **Changes Made**

- [x] Add Styles
- [x] Update Btn
- [x] Update Slice btns styles
- [x] Update Back Btn
### **Screenshots:**
image
image
image

### CODE REVIEW

**Review by ClaudiaRojasSoto — CHANGES_REQUESTED** [review]
Hello @PabloBona, good job so far!!!!
Your design is incredible and looks very professional.
Your commits are very professional as well.
However, the user data that appears with auto fill must be added since the requirements demand it.
In the code I worked on this data appears and was a headache, could you please consider including it to meet the requirements?

Greetings,
@ClaudiaRojasSoto

**Comment by PabloBona** [comment]
image
image

**Comment by PabloBona** [comment]
Hello @ClaudiaRojasSoto,

Thank you for your feedback and kind words about my work so far. I appreciate your acknowledgment of the design and professionalism in my commits. I understand your concern regarding the user data auto fill requirement.

I have reviewed the code, and I apologize for the oversight. I will make sure to include the necessary user data auto fill feature as per the requirements. Rest assured, I will address this issue promptly to ensure that all requirements are met.

Thank you for bringing this to my attention, and please feel free to reach out if you have any more specific requests or concerns.

Best regards,
@PabloBona

**Review by ClaudiaRojasSoto — APPROVED** [review]
Thank you @PabloBona. 
Your work is complete and looks amazing!!!.
There is nothing more to say other than is time to merge.

Greetings,
@ClaudiaRojasSoto

**Pull request merged**
